image: maven:latest

stages:
  - build
  - Test
  - deploy

build:
  only:
    - merge_requests
  stage: build
  tags: ["dalfcs_docker_kvm", "dalfcs_gitlab_docker_ci"]
  script: 
      - "mvn compile"
Test:
  stage: Test
  only:
    - merge_requests
  tags: ["dalfcs_docker_kvm", "dalfcs_gitlab_docker_ci"]
  script:
    - "mvn test"
    - "mvn package"
  artifacts:
    expire_in: 1 week
    paths:
       - target/MyApp.jar
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
